import asyncio
import logging
import os

import discord
from discord.ext import commands
from config import DISCORD_BOT_TOKEN, COMMAND_PREFIX, CLI_TOOLS

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("bot")

intents = discord.Intents.default()
intents.message_content = True

bot = commands.Bot(command_prefix=COMMAND_PREFIX, intents=intents, help_command=None)

COGS = [
    "cogs.ai_cli",
    "cogs.executor",
    "cogs.status",
    "cogs.help_cmd",
]


# ---------------------------------------------------------------------------
# Startup interactive setup
# ---------------------------------------------------------------------------
def startup_setup() -> tuple[str, str]:
    """Ask which CLI tool to use and which folder to work in.

    Returns (cli_name, working_directory).
    """
    tools = list(CLI_TOOLS.items())

    print()
    print("=" * 48)
    print("  AI CLI Gateway Bot")
    print("=" * 48)

    # --- 1) CLI tool selection ---
    print()
    print("  [1/2] Select AI CLI tool:")
    print()
    for i, (key, tool) in enumerate(tools, 1):
        print(f"    {i}) {tool['name']}  ({key})")
    print()

    while True:
        raw = input(f"  Enter number [1-{len(tools)}] (default: 1): ").strip()
        if raw == "":
            cli_name = tools[0][0]
            break
        if raw.isdigit() and 1 <= int(raw) <= len(tools):
            cli_name = tools[int(raw) - 1][0]
            break
        print("  Invalid choice, try again.")

    tool_name = CLI_TOOLS[cli_name]["name"]
    print(f"  -> {tool_name} selected!")

    # --- 2) Working directory ---
    print()
    print("  [2/2] Enter working directory:")
    print(f"        (The folder where {tool_name} will run)")
    print()

    while True:
        cwd = input(f"  Path (default: {os.getcwd()}): ").strip()
        if cwd == "":
            cwd = os.getcwd()
        # Strip surrounding quotes if user pasted a path with them
        cwd = cwd.strip('"').strip("'")
        if os.path.isdir(cwd):
            break
        print(f"  '{cwd}' is not a valid directory. Try again.")

    cwd = os.path.abspath(cwd)
    print(f"  -> Working directory: {cwd}")
    print()
    print("=" * 48)
    print(f"  {tool_name}  @  {cwd}")
    print("=" * 48)
    print()

    ensure_rules_md(cli_name, cwd)

    return cli_name, cwd


# ---------------------------------------------------------------------------
# Rules MD — project rules injected into the working directory
# ---------------------------------------------------------------------------
_RULES_MARKER = "# [AIDevelop Bot Rules]"

_RULES_TEMPLATE = """\
# [AIDevelop Bot Rules]
# Auto-generated by AIDevelop bot — do not remove this section.

## Working Directory Restriction
- You MUST only read, write, and modify files within this project directory.
- Do NOT access or modify files outside of this folder.
- Shell commands must only operate within this directory.

## Allowed Actions
- File operations (read, write, edit, search) — within this folder only
- Shell commands — within this folder only
- Web search and web fetch — allowed
"""


def ensure_rules_md(cli_name: str, cwd: str) -> None:
    """Create or append bot rules to the CLI's rules file in cwd."""
    tool = CLI_TOOLS[cli_name]
    filename = tool.get("rules_file", "CLAUDE.md")
    md_path = os.path.join(cwd, filename)

    if os.path.isfile(md_path):
        with open(md_path, "r", encoding="utf-8") as f:
            content = f.read()
        if _RULES_MARKER in content:
            print(f"  [{filename}] Rules already present")
            return
        with open(md_path, "a", encoding="utf-8") as f:
            f.write("\n\n" + _RULES_TEMPLATE)
        print(f"  [{filename}] Appended rules to {md_path}")
    else:
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(_RULES_TEMPLATE)
        print(f"  [{filename}] Created {md_path}")


# ---------------------------------------------------------------------------
# Events
# ---------------------------------------------------------------------------
@bot.event
async def on_ready():
    tool = CLI_TOOLS[bot.selected_cli]
    log.info("Logged in as %s (ID: %s)", bot.user, bot.user.id)
    log.info("Connected to %d guild(s)", len(bot.guilds))
    log.info("Active CLI: %s  |  CWD: %s", tool["name"], bot.working_dir)
    folder_name = os.path.basename(bot.working_dir)
    await bot.change_presence(
        activity=discord.Activity(
            type=discord.ActivityType.listening,
            name=f"{tool['name']} @ {folder_name}",
        )
    )


@bot.event
async def on_command_error(ctx: commands.Context, error: commands.CommandError):
    if isinstance(error, commands.CheckFailure):
        return
    if isinstance(error, commands.CommandNotFound):
        return
    if isinstance(error, commands.MissingRequiredArgument):
        await ctx.reply(f"Missing argument: `{error.param.name}`. Use `{COMMAND_PREFIX}help` for usage.")
        return
    log.error("Unhandled command error: %s", error, exc_info=error)
    await ctx.reply(f"An error occurred: `{error}`")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
async def main():
    if not DISCORD_BOT_TOKEN:
        log.error("DISCORD_BOT_TOKEN is not set. Check your .env file.")
        return

    async with bot:
        for cog in COGS:
            try:
                await bot.load_extension(cog)
                log.info("Loaded cog: %s", cog)
            except Exception as e:
                log.error("Failed to load cog %s: %s", cog, e)
        await bot.start(DISCORD_BOT_TOKEN)


if __name__ == "__main__":
    selected_cli, working_dir = startup_setup()
    bot.selected_cli = selected_cli
    bot.working_dir = working_dir
    asyncio.run(main())
